on:
  workflow_dispatch:
    inputs:
      message:
        description: 'Message'
        type: string

jobs:
  print-message:
    runs-on: ubuntu-latest
    steps:
      - name: 'Print the message from inputs'
        run: echo "inputs.message: " ${{ inputs.message }}
    steps:
      - name: 'Set ENV if inputs given'
        if: ${{ inputs.message != '' }}
        env:
          MESSAGE: ${{ inputs.message }}
    steps:
      - name: 'Print env MESSAGE'
        run: echo "$MESSAGE"
