on:
  workflow_dispatch:
    inputs:
      message:
        description: 'Message'
        type: string

jobs:
  print-message:
    runs-on: ubuntu-latest
    steps:
      - name: 'Set ENV if inputs given'
        if: ${{ inputs.message != '' }}
        env:
          MESSAGE: ${{ inputs.message }}
        run: echo "Set environment variable"
      - name: 'Print env MESSAGE'
        run: echo "$MESSAGE"
      - name: 'Check MESSAGE exists'
        run: printenv | grep MESSAGE
